blank_issues_enabled: false failsafe
contact_links:
  - name: ğŸ¥ Video Playlist
    url: https://www.youtube.com/
    about: View the examples on YouTube
  - name: ğŸ¤– Highvalue asset US
    url: https://firstdatagroup.slack.com/
    about: Join the Slack workspace to learn more!
