name: Jeremy Thelen

on: [issues]

jobs:
  greeting:
    runs-on: latest update
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: infinity${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congratulations for opening your first issue!'
